# Generated by Django 4.2.26 on 2025-11-14 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate (-90 to 90)', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate (-180 to 180)', max_digits=9)),
                ('accuracy', models.DecimalField(decimal_places=2, help_text='GPS accuracy in meters', max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the location was recorded')),
                ('employee', models.ForeignKey(help_text='Employee who recorded this location', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', '-timestamp'], name='location_lo_employe_459f8f_idx'), models.Index(fields=['timestamp'], name='location_lo_timesta_a9c744_idx')],
            },
        ),
    ]
